prms={
      "name",
      "age",
      "gender",
      "reportedOn"
      "LDL/HDL Ratio",
      "HDL Cholesterol",
      "LDL Particle Number",
      "Cholesterol / HDL Ratio",
      "Total Cholesterol",
      "LDL Cholesterol",
      "Non-HDL Cholesterol",
      "VLDL",
      "HDL/LDL Ratio",
      "Triglycerides",
      "Apolipoprotein B (Apo B)",
      "Thyroxine (T4) Free",
      "Thyroid-Stimulating Hormone (TSH)",
      "Iodine",
      "Triiodothyronine (T3) Free",
      "Selenium",
      "PSA Free Percentage",
      "PSA Total",
      "Rheumatoid Factor",
      "Antinuclear Antibodies ANA Titer",
      "Iron Binding Capacity (TIBC)",
      "Omega-6 Total",
      "Vitamin D",
      "Ferritin",
      "Omega-3 Total",
      "Methylmalonic Acid (MMA)",
      "Copper",
      "Zinc",
      "Omega-6: Linoleic Acid",
      "Iron % Saturation",
      "Magnesium",
      "Vitamin B12",
      "Omega-3: EPA+DPA+DHA",
      "Iron",
      "Omega-6: Arachidonic Acid",
      "Homocysteine",
      "Omega-6 / Omega-3 Ratio",
      "Calcium",
      "Arachidonic Acid/EPA Ratio",
      "Aspartate Transaminase (AST)",
      "Total Protein",
      "Globulin",
      "Total Bilirubin",
      "Alkaline Phosphatase (ALP)",
      "Albumin",
      "Gamma-glutamyl Transferase (GGT)",
      "Alanine Transaminase (ALT)",
      "Estimated Glomerular Filtration Rate (eGFR)",
      "Chloride",
      "Blood Urea Nitrogen (BUN)",
      "Albumin (Microalbumin) - Urine",
      "BUN / Creatinine Ratio",
      "Creatinine",
      "Sodium",
      "Potassium",
      "Absolute Eosinophils count",
      "High-Sensitivity C-Reactive Protein (hs-CRP)",
      "Lymphocytes",
      "Eosinophils",
      "Absolute Basophils count",
      "Absolute Monocytes count",
      "Absolute Neutrophils count",
      "Basophils",
      "Neutrophils",
      "Monocytes",
      "NLR",
      "Absolute Lymphocytes count",
      "White Blood Cell Count (WBC)",
      "Adiponectin",
      "Uric Acid",
      "Hemoglobin A1c (HbA1c)",
      "Leptin",
      "Glucose",
      "Insulin",
      "Insulin-like Growth Factor (IGF-1)",
      "Cortisol",
      "Amylase",
      "Lipase",
      "Mercury",
      "Lead",
      "Arsenic",
      "Aluminum",
      "Mean Corpuscular Volume (MCV)",
      "Hematocrit",
      "Mean Corpuscular Hemoglobin Concentration (MCHC)",
      "Mean Corpuscular Hemoglobin (MCH)",
      "Red Cell Distribution Width (RDW)",
      "Red Blood Cell (RBC) Count",
      "Platelet Count",
      "Hemoglobin",
      "Mean Platelet Volume (MPV)",
      "Carbon Dioxide (CO2)",
      "Phosphorus",
      "Bilirubin",
      "Conjugated Bilirubin",
      "Red Blood Cell (RBC)",
      "White Blood Cell (WBC)",
      "pH",
      "Ketones",
      "Protein",
      "Unconjugated Bilirubin",
      "Specific Gravity",
      "Glucose-Urine",
      "HIV 1 & 2 Antigen-Antibody",
      "Herpes Simplex Virus 1 and 2",
      "Phosphorus",
      "Conjugated Bilirubin",
      "Unconjugated Bilirubin",
      "Absolute Neutrophils count",
      "Absolute Lymphocytes count",
      "Absolute Monocytes count",
      "Absolute Eosinophils count",
      "Absolute Basophils count",
      "NLR",
      "LDL/HDL Ratio",
      "HDL/LDL Ratio",
      "VLDL",
      "Vitamin B12",

}
prmss={"Name",
"Age",
"Gender",
"ReportedOn",
"Hemoglobin",
"WBC",
"RBC",
"MCV",
"MCH",
"MCHC",
"Hematocrit",
"RDW",
"Platelet Count",
"MPV",
"Neutrophils",
"Lymphocytes",
"Monocytes",
"Eosinophils",
"Basophils",
"ESR",
"Absolute Neutrophils count",
"Absolute Lymphocytes count",
"Absolute Monocytes count",
"Absolute Eosinophils count",
"Absolute Basophils count",
"NLR",
"HbA1C",
"Mean Blood Glucose",
"Triiodothyronine",
"Thyroxine",
"Thyroid Stimulating Hormone",
"Vitamin B12",
"Vitamin D",
"Testosterone",
"Cortisol",
"Cholesterol",
"Triglycerides",
"HDL",
"Non-HDL",
"LDL",
"VLDL",
"LDL/HDL Ratio",
"HDL/LDL Ratio",
"CHOL/HDL Ratio",
"CRP",
"Creatinine",
"BUN/Creatinine Ratio",
"Urea",
"Uric Acid",
"Blood Urea Nitrogen",
"Calcium",
"Phosphorus",
"SGPT",
"SGOT",
"eGFR",
"Sodium",
"Potassium",
"Chloride",
"Magnesium",
"LDH",
"Total Bilirubin",
"Conjugated Bilirubin",
"Unconjugated Bilirubin",
"AST",
"ALT",
"AST/ALT Ratio",
"ALP",
"GGT",
"Protein",
"Albumin",
"Globulin",
"A/G Ratio",
"Rheumatoid Factor",
"Lipoprotein"
      }